name: Tests

on:
  push:
    branches: [ main, fix-ci-v-0-2 ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: invariantlabs-ai/invariant-gateway
        ref: mcp-metadata
        path: ${{ github.workspace }}/invariant-gateway
    - name: Write .env
      run: |
        echo "INVARIANT_GATEWAY_DIR=${{ github.workspace }}/invariant-gateway" > .env
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: Create venv
      run: uv venv
    - name: Run tests
      run: make test
